alias p3='/usr/bin/python3'
alias ip3='/usr/local/bin/ipython3'
alias ip3n='/usr/local/bin/ipython3 notebook'
alias mns='cd /home/mr_user/Dropbox/Schule/TU_Berlin/MNS'
alias mi='cd /home/mr_user/Dropbox/Schule/TU_Berlin/Machine_Intelligence'
alias mohr='cd /home/mr_user/Dropbox/Schule/TU_Berlin/Mohr_NI_Lab/scripts'
alias alioth='ssh gknoll@130.149.250.12'
alias win='dolphin . &'
alias gitlogp='git log --pretty=format:"%h-->%cn, %cd :%n%s%n" --graph --stat --date=local'
