alias jup='cd /home/mr_user/Dropbox/Schule/TU_Berlin && jupyter notebook'
alias aande='cd ~/Dropbox/Schule/TU_Berlin/AAND/exercises'
alias mns='cd /home/mr_user/Dropbox/Schule/TU_Berlin/MNS'
alias tu='cd ~/Dropbox/Schule/TU_Berlin/'
alias mi='cd /home/mr_user/Dropbox/Schule/TU_Berlin/Machine_Intelligence'
alias mohr='cd /home/mr_user/Dropbox/Schule/TU_Berlin/Mohr_NI_Lab/scripts'
alias psc='cd /home/mr_user/Workspace/phd_codebase/detector_param_estimation'
alias alioth='ssh gknoll@130.149.250.12'
alias win='dolphin . &'
alias gitlogp='git log --pretty=format:"%h-->%cn, %cd :%n%n%s%n" --graph --decorate --stat --date=local'
alias netwreset='/etc/init.d/network-manager restart'
alias tuvpn='sudo openconnect vpn.tu-berlin.de -u gregknoll@win.tu-berlin.de'
alias dbrestart='dropbox stop && DBUS_SESSION_BUS_ADDRESS="" dropbox start'
alias kdm='cd /home/mr_user/Workspace/kingdom-death-monster'
alias xilinx='/opt/Xilinx/14.7/ISE_DS/run_ise.sh'
alias alchitry='~/Software/Linux/fpga/alchitry-labs-1.0.5/alchitry-labs'
